info:
  application:
    version: v1
    name: channel
  project:
    displayName: KUDP
  tenant:
    displayName: KOREA
    id:
  client:
    displayName: psdn-multi-tenant-app
    id:
    secret:
  remote-server:
    system:
      base-url: "http://localhost:8999"
    entra:
      base-url: "https://graph.microsoft.com/"
    synapse:
      base-url: ""

server:
  port: 7999
  servlet:
    context-path: /${info.application.version}/tenants/${info.tenant.displayName}/${info.project.displayName}/${spring.application.name}

spring:
  application:
    name: ${info.application.name}
