info:
  application:
    version: v1
    name: channel
  project:
    name: KUDP
  tenant:
    id:
    name: KOREA
  client:
    id:
    secret:
    name: psdn-multi-tenant-app
  remote-server:
    system:
      base-url: "http://localhost:8999/v1/tenants/KOREA/KUDP/system"
    entra:
      base-url: "https://graph.microsoft.com/"
    synapse:
      base-url: ""

server:
  port: 7999
  servlet:
    context-path: "/${info.application.version}/tenants/${info.tenant.name}/${info.project.name}/${info.application.name}"

spring:
  application:
    name: channel
